import { createContext, useContext, useState } from 'react';

const T = {
  es: {
    app_name: 'Humantric',
    app_sub:  'Métrica del humano',
    tab_today:    '✅ Hoy',
    tab_history:  '📅 Historial',
    tab_metrics:  '📊 Métricas',
    logout:       'Cerrar sesión',
    guest_label:  'Invitado',
    guest_exit:   'Salir',
    guest_banner: 'Modo invitado — crea una cuenta para guardar tu progreso.',
    guest_register_now: 'Crear cuenta',
    guest_btn:    'Continuar como invitado',
    guest_note:   'Sin registro · Solo explorar · Los datos no se guardan',
    guest_save_blocked: 'Crea una cuenta gratuita para guardar tu progreso.',
    or: 'o',
    login_title:    'Bienvenido de vuelta',
    register_title: 'Crear cuenta',
    username:    'Usuario',
    password:    'Contraseña',
    confirm_pw:  'Confirmar contraseña',
    btn_login:   'Entrar',
    btn_register:'Registrarse',
    go_register: '¿No tienes cuenta? Regístrate',
    go_login:    '¿Ya tienes cuenta? Inicia sesión',
    err_fields:     'Completa todos los campos.',
    err_short_user: 'El usuario debe tener al menos 3 caracteres.',
    err_short_pw:   'La contraseña debe tener al menos 4 caracteres.',
    err_pw_match:   'Las contraseñas no coinciden.',
    err_connection: 'Error de conexión.',
    ok_registered:  '¡Cuenta creada! Ya puedes iniciar sesión.',
    connecting:     'Conectando...',
    loading:        'Cargando...',
    // Today
    today_title:   'Tu día de hoy',
    today_sub:     'Marca los hábitos que completaste',
    save_day:      'Guardar mi día',
    saving:        'Guardando...',
    saved_ok:      '¡Día guardado correctamente!',
    err_save:      'Error al guardar.',
    already_saved: 'Ya guardaste este día. ¿Quieres actualizarlo?',
    update_day:    'Actualizar',
    score_today:   'Tu score de hoy',
    habits_done:   'hábitos completados',
    // Score labels
    score_great: '¡Excelente día!',
    score_good:  'Buen día',
    score_fair:  'Día regular',
    score_low:   'Día difícil',
    score_risk:  'Necesitas atención',
    // Alert
    alert_yellow: '⚠️ Tu bienestar ha bajado varios días seguidos. Intenta retomar algunos hábitos.',
    alert_red:    '🔴 Tu bienestar lleva varios días en riesgo. Considera hablar con alguien de confianza.',
    // Categories
    cat_physical:    'Físico',
    cat_mental:      'Mental',
    cat_social:      'Social',
    cat_environment: 'Entorno',
    cat_purpose:     'Propósito',
    // Habits
    habit_sleep:          'Dormí bien (7+ horas)',
    habit_exercise:       'Hice ejercicio hoy',
    habit_water:          'Bebí suficiente agua',
    habit_nutrition:      'Comí saludable',
    habit_sunlight:       'Salí al exterior / luz solar',
    habit_no_alcohol:     'No consumí alcohol',
    habit_no_substances:  'No consumí sustancias',
    habit_meditation:     'Medité o respiración consciente',
    habit_reading:        'Leí al menos 20 minutos',
    habit_no_screens:     'Pasé tiempo sin pantallas',
    habit_learning:       'Aprendí algo nuevo',
    habit_journaling:     'Escribí en un diario / reflexioné',
    habit_conversation:   'Tuve una conversación significativa',
    habit_quality_time:   'Pasé tiempo con alguien que me importa',
    habit_helped_someone: 'Ayudé a alguien hoy',
    habit_no_conflicts:   'Evité conflictos innecesarios',
    habit_tidiness:       'Mantuve mi espacio ordenado',
    habit_nature:         'Pasé tiempo en naturaleza',
    habit_calm_env:       'Mi entorno fue tranquilo',
    habit_goal_progress:  'Avancé en una meta personal',
    habit_creativity:     'Hice algo creativo',
    habit_productive:     'Me sentí productivo hoy',
    // History
    no_data_day:   'Sin registro para este día',
    editing_past:        'Editando día pasado',
    go_today:            'Ir a hoy',
    reflection_label:    'Reflexión del día',
    reflection_placeholder: '¿Cómo te sentiste hoy? ¿Algo que quieras recordar?',
    // Metrics
    metrics_title:   'Tus métricas',
    streak_days:     'días de racha',
    avg_score:       'Score promedio',
    best_score:      'Mejor día',
    total_days:      'Días registrados',
    progress_chart:  'Progreso',
    best_vs_worst:   'Mejor vs Peor semana',
    week_of:         'Semana del',
    best_week:       'Mejor semana',
    worst_week:      'Peor semana',
    no_metrics:      'Registra al menos un día para ver tus métricas.',
    days_short:      'd',
    months: ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
    weekdays: ['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'],
  },
  en: {
    app_name: 'Humantric',
    app_sub:  'Human Metrics',
    tab_today:    '✅ Today',
    tab_history:  '📅 History',
    tab_metrics:  '📊 Metrics',
    logout:       'Sign out',
    guest_label:  'Guest',
    guest_exit:   'Exit',
    guest_banner: 'Guest mode — create an account to save your progress.',
    guest_register_now: 'Create account',
    guest_btn:    'Continue as Guest',
    guest_note:   'No sign up · Just explore · Data won\'t be saved',
    guest_save_blocked: 'Create a free account to save your progress.',
    or: 'or',
    login_title:    'Welcome back',
    register_title: 'Create account',
    username:    'Username',
    password:    'Password',
    confirm_pw:  'Confirm password',
    btn_login:   'Sign in',
    btn_register:'Register',
    go_register: 'No account? Register here',
    go_login:    'Already have an account? Sign in',
    err_fields:     'Please fill in all fields.',
    err_short_user: 'Username must be at least 3 characters.',
    err_short_pw:   'Password must be at least 4 characters.',
    err_pw_match:   'Passwords do not match.',
    err_connection: 'Connection error.',
    ok_registered:  'Account created! You can now sign in.',
    connecting:     'Connecting...',
    loading:        'Loading...',
    today_title:   'Your day',
    today_sub:     'Check the habits you completed today',
    save_day:      'Save my day',
    saving:        'Saving...',
    saved_ok:      'Day saved successfully!',
    err_save:      'Error saving.',
    already_saved: 'You already saved today. Update it?',
    update_day:    'Update',
    score_today:   "Today's score",
    habits_done:   'habits completed',
    score_great: 'Outstanding day!',
    score_good:  'Good day',
    score_fair:  'Average day',
    score_low:   'Rough day',
    score_risk:  'Needs attention',
    alert_yellow: '⚠️ Your wellbeing has been dropping for several days. Try to pick up some habits.',
    alert_red:    '🔴 Your wellbeing has been at risk for several days. Consider talking to someone you trust.',
    cat_physical:    'Physical',
    cat_mental:      'Mental',
    cat_social:      'Social',
    cat_environment: 'Environment',
    cat_purpose:     'Purpose',
    habit_sleep:          'Slept well (7+ hours)',
    habit_exercise:       'Exercised today',
    habit_water:          'Drank enough water',
    habit_nutrition:      'Ate healthy',
    habit_sunlight:       'Got outside / sunlight',
    habit_no_alcohol:     'No alcohol',
    habit_no_substances:  'No substances',
    habit_meditation:     'Meditated or breathwork',
    habit_reading:        'Read for 20+ minutes',
    habit_no_screens:     'Spent time off screens',
    habit_learning:       'Learned something new',
    habit_journaling:     'Journaled or self-reflected',
    habit_conversation:   'Had a meaningful conversation',
    habit_quality_time:   'Spent time with someone I care about',
    habit_helped_someone: 'Helped someone today',
    habit_no_conflicts:   'Avoided unnecessary conflicts',
    habit_tidiness:       'Kept my space tidy',
    habit_nature:         'Spent time in nature',
    habit_calm_env:       'My environment was calm',
    habit_goal_progress:  'Made progress on a personal goal',
    habit_creativity:     'Did something creative',
    habit_productive:     'Felt productive today',
    no_data_day:   'No record for this day',
    editing_past:        'Editing past day',
    go_today:            'Go to today',
    reflection_label:    'Daily reflection',
    reflection_placeholder: 'How did you feel today? Anything you want to remember?',
    metrics_title:   'Your metrics',
    streak_days:     'day streak',
    avg_score:       'Average score',
    best_score:      'Best day',
    total_days:      'Days logged',
    progress_chart:  'Progress',
    best_vs_worst:   'Best vs Worst week',
    week_of:         'Week of',
    best_week:       'Best week',
    worst_week:      'Worst week',
    no_metrics:      'Log at least one day to see your metrics.',
    days_short:      'd',
    months: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
    weekdays: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
  },
};

const LangContext = createContext();
export function LangProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem('h_lang') || 'es');
  const changeLang = (l) => { setLang(l); localStorage.setItem('h_lang', l); };
  const t = (k) => T[lang][k] ?? k;
  return <LangContext.Provider value={{ lang, changeLang, t }}>{children}</LangContext.Provider>;
}
export function useLang() { return useContext(LangContext); }
